---
global:
  folder: files
cases:
- tt_members: Student 01 PY
  filename: student1/math.py
- tt_members: Student 02 PY
  filename: student2/math.py
- tt_members: Student 03 RB
  filename: student3/math.rb
- tt_members: Student 04 NONE
  filename: student4/none